### ISSUE TITLE
Installation instructions?

### ISSUE THREAD

**Issue by vgc** [EllisLab/Word-Limit#3]
Sorry, I just can't figure out where to put the char_limit folder.

I tried system/expressionengine/third_party/char_limit without success. 

Can you please help? Thank you!

EE v2.10.1

**Comment by kevincupp** [comment]
That is the correct location. Make sure you've downloaded the 2.x version and not the 3.x version: https://github.com/EllisLab/Word-Limit/tree/2.x

**Comment by vgc** [comment]
OK great, that works, but now I am getting PHP warnings at the top of my page:

http://www.vanhove.net/max/index.php/services/category/training-classes

Message: Non-static method Eehive_hacksaw::usage() should not be called statically, assuming $this from incompatible context
Filename: eehive_hacksaw/pi.eehive_hacksaw.php
Line Number: 11

A PHP Error was encountered
Severity: Warning
Message: Cannot modify header information - headers already sent by (output started at /home/vgc/public_html/max/UcBfU-U6yBmW2/codeigniter/system/core/Exceptions.php:170)
Filename: core/Common.php
Line Number: 475

Is there a fix for this?

Thank you!

**Comment by kevincupp** [comment]
That looks unrelated to this plugin, looks like the error is coming from pi.eehive_hacksaw.php. Can you open and edit that file? You should just need to find:

```php
function usage() {
```

And change it to:

```php
public static function usage() {
```

**Comment by vgc** [comment]
Hmm that is so strange ... I could swear I downloaded hacksaw from this repository where the 2.x word_limit was supposed to be (I thought that was the 2.x word_limit).

Anyway, I do have the word_limit plugin in place now, it is doing just what I need, and correctly. :)

I thank you so much for your help, enjoy the rest of your day!

Steve

**Comment by kevincupp** [comment]
Sure thing!
